baseURL = "https://83problems.com/"
languageCode = "en-us"
title = "Because we all have 83 problems"
theme = "cactus"
copyright = "Brian Gribble"

[[menu.main]]
name = "Home"
url = "/" 
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  colortheme = "dark"
  rss = true
  description = "A quiet corner to showcase some skills, maybe write a little, and list my graveyard of projects."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "" # title link for projects list
                                                                                                        
  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/83problems"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/brian-gribble"
  [[params.social]]
    name = "email"
    link = "contact@83problems.com"  # no need for "mailto:" in the head
